import { questions } from "../data/questions.js";

const createAnswers = (optionIds) => {
  if (optionIds.length !== questions.length) {
    throw new Error(`Personai vajadzīgas ${questions.length} atbildes.`);
  }
  return questions.map((question, index) => ({
    questionId: question.id,
    optionId: optionIds[index],
  }));
};

export const personas = [
  {
    id: "persona_textile_designer",
    targetProfessionId: "apgerbu_dizainera_asistents",
    rationale: "Vizuāls tekstila izstrādājums, rūpīga piegrieztne un pacietīgs darbs darbnīcā.",
    answers: createAnswers([
      "q01_textile",
      "q02_unsure",
      "q03_clothing",
      "q04_garment",
      "q05_surface",
      "q06_concept",
      "q07_craft_workshop",
      "q08_building_plan",
      "q09_sawdust",
      "q10_prototype",
      "q11_unsure",
      "q12_noisy_workshop",
      "q13_making_tools",
      "q14_sketch",
      "q15_crafted",
      "q16_visual",
      "q17_heavy_outdoor",
      "q18_design_build",
    ]),
  },
  {
    id: "persona_agricultural_machinery",
    targetProfessionId: "lauksaimniecibas_mehanizacijas_tehnikis",
    rationale: "Lielas mašīnas, mehāniska diagnostika, fizisks darbs un saimniecības vide.",
    answers: createAnswers([
      "q01_mechanism",
      "q02_engine",
      "q03_crop",
      "q04_agri_machine",
      "q05_measurement",
      "q06_build",
      "q07_field",
      "q08_machine_noise",
      "q09_weather",
      "q10_practical",
      "q11_field",
      "q12_code_screen",
      "q13_vehicle_tools",
      "q14_inspect_object",
      "q15_immediate_repair",
      "q16_durable",
      "q17_solo_screen",
      "q18_field_trial",
    ]),
  },
  {
    id: "persona_crop_grower",
    targetProfessionId: "augkopibas_tehnikis",
    rationale: "Augu novērojumi, sezonāls process, lauka dati un darbs ārā.",
    answers: createAnswers([
      "q01_unsure",
      "q02_unsure",
      "q03_crop",
      "q04_unsure",
      "q05_measurement",
      "q06_research",
      "q07_field",
      "q08_plant_stress",
      "q09_weather",
      "q10_quality",
      "q11_field",
      "q12_code_screen",
      "q13_unsure",
      "q14_test_logic",
      "q15_season",
      "q16_clever",
      "q17_solo_screen",
      "q18_field_trial",
    ]),
  },
  {
    id: "persona_furniture_maker",
    targetProfessionId: "mebelu_galdnieks",
    rationale: "Precīzi koka savienojumi, tīra virsma un ilgstoša patstāvīga meistarība darbnīcā.",
    answers: createAnswers([
      "q01_wood",
      "q02_unsure",
      "q03_furniture",
      "q04_unsure",
      "q05_joint",
      "q06_build",
      "q07_craft_workshop",
      "q08_building_plan",
      "q09_sawdust",
      "q10_practical",
      "q11_unsure",
      "q12_outdoors",
      "q13_making_tools",
      "q14_sketch",
      "q15_crafted",
      "q16_precise",
      "q17_heavy_outdoor",
      "q18_design_build",
    ]),
  },
  {
    id: "persona_finishing",
    targetProfessionId: "apdares_darbu_tehnikis",
    rationale: "Redzama telpas pārvērtība, materiālu izjūta, precīza virsma un praktisks darbs.",
    answers: createAnswers([
      "q01_textile",
      "q02_surface",
      "q03_finish",
      "q04_garment",
      "q05_surface",
      "q06_concept",
      "q07_craft_workshop",
      "q08_building_plan",
      "q09_site_dust",
      "q10_practical",
      "q11_unsure",
      "q12_code_screen",
      "q13_unsure",
      "q14_inspect_object",
      "q15_crafted",
      "q16_visual",
      "q17_solo_screen",
      "q18_design_build",
    ]),
  },
  {
    id: "persona_building_coordinator",
    targetProfessionId: "eku_buvtehnikis",
    rationale: "Rasējumu pārvēršana darba secībā, komandas koordinēšana, kvalitāte un būvobjekts.",
    answers: createAnswers([
      "q01_wood",
      "q02_circuit",
      "q03_finish",
      "q04_frame",
      "q05_drawing",
      "q06_coordinate",
      "q07_building_site",
      "q08_building_plan",
      "q09_site_dust",
      "q10_coordinate",
      "q11_structure",
      "q12_code_screen",
      "q13_cad",
      "q14_team_plan",
      "q15_long_build",
      "q16_team",
      "q17_solo_screen",
      "q18_design_build",
    ]),
  },
  {
    id: "persona_carpenter",
    targetProfessionId: "namdaris",
    rationale: "Pilna izmēra koka konstrukcijas, fiziska montāža objektā un komandas darbs ārā.",
    answers: createAnswers([
      "q01_wood",
      "q02_engine",
      "q03_furniture",
      "q04_frame",
      "q05_joint",
      "q06_build",
      "q07_building_site",
      "q08_building_plan",
      "q09_sawdust",
      "q10_practical",
      "q11_structure",
      "q12_code_screen",
      "q13_making_tools",
      "q14_inspect_object",
      "q15_long_build",
      "q16_durable",
      "q17_solo_screen",
      "q18_design_build",
    ]),
  },
  {
    id: "persona_architecture",
    targetProfessionId: "arhitekturas_tehnikis",
    rationale: "Telpisks modelis, rasējumu precizitāte, vizuāla domāšana un koncentrēts darbs pie datora.",
    answers: createAnswers([
      "q01_digital_tool",
      "q02_code",
      "q03_finish",
      "q04_garment",
      "q05_drawing",
      "q06_concept",
      "q07_digital_lab",
      "q08_building_plan",
      "q09_screen_focus",
      "q10_prototype",
      "q11_structure",
      "q12_noisy_workshop",
      "q13_cad",
      "q14_sketch",
      "q15_digital",
      "q16_visual",
      "q17_heavy_outdoor",
      "q18_design_build",
    ]),
  },
  {
    id: "persona_building_systems",
    targetProfessionId: "inzeniersistemu_buvtehnikis",
    rationale: "Ēku sistēmu shēmas, elektrība, telpiska koordinēšana un montāžas kvalitāte objektā.",
    answers: createAnswers([
      "q01_computer_fix",
      "q02_circuit",
      "q03_finish",
      "q04_frame",
      "q05_measurement",
      "q06_coordinate",
      "q07_building_site",
      "q08_building_plan",
      "q09_site_dust",
      "q10_coordinate",
      "q11_electrical",
      "q12_code_screen",
      "q13_cad",
      "q14_safe_manual",
      "q15_long_build",
      "q16_team",
      "q17_solo_screen",
      "q18_design_build",
    ]),
  },
  {
    id: "persona_computer_systems",
    targetProfessionId: "datorsistemu_tehnikis",
    rationale: "Datoru komponentes, tīkla signālu diagnostika, sistemātiska pārbaude un koncentrēšanās.",
    answers: createAnswers([
      "q01_computer_fix",
      "q02_network",
      "q03_unsure",
      "q04_software",
      "q05_measurement",
      "q06_test",
      "q07_digital_lab",
      "q08_connectivity",
      "q09_screen_focus",
      "q10_analyse",
      "q11_digital",
      "q12_noisy_workshop",
      "q13_network_tools",
      "q14_safe_manual",
      "q15_immediate_repair",
      "q16_clever",
      "q17_heavy_outdoor",
      "q18_smart_lab",
    ]),
  },
  {
    id: "persona_programmer",
    targetProfessionId: "programmesanas_tehnikis",
    rationale: "Algoritmi, atkļūdošana, digitālas iterācijas un ilgstoša patstāvīga koncentrēšanās.",
    answers: createAnswers([
      "q01_digital_tool",
      "q02_code",
      "q03_unsure",
      "q04_software",
      "q05_logic",
      "q06_research",
      "q07_digital_lab",
      "q08_automate",
      "q09_screen_focus",
      "q10_analyse",
      "q11_digital",
      "q12_noisy_workshop",
      "q13_debugger",
      "q14_test_logic",
      "q15_digital",
      "q16_clever",
      "q17_heavy_outdoor",
      "q18_app",
    ]),
  },
  {
    id: "persona_auto_mechanic",
    targetProfessionId: "automehanikis",
    rationale: "Slēpta mehāniska bojājuma atrašana, mērījumi, praktisks remonts un tūlītēja pārbaude.",
    answers: createAnswers([
      "q01_mechanism",
      "q02_engine",
      "q03_bodywork",
      "q04_engine",
      "q05_measurement",
      "q06_test",
      "q07_auto_shop",
      "q08_machine_noise",
      "q09_grease_metal",
      "q10_analyse",
      "q11_vehicle",
      "q12_code_screen",
      "q13_vehicle_tools",
      "q14_inspect_object",
      "q15_immediate_repair",
      "q16_clever",
      "q17_solo_screen",
      "q18_vehicle_restore",
    ]),
  },
  {
    id: "persona_bodywork",
    targetProfessionId: "autovirsbuvju_remonta_tehnikis",
    rationale: "Metāla formas atjaunošana, virsmas kvalitāte, redzama pārvērtība un praktiska precizitāte.",
    answers: createAnswers([
      "q01_mechanism",
      "q02_engine",
      "q03_bodywork",
      "q04_engine",
      "q05_surface",
      "q06_build",
      "q07_auto_shop",
      "q08_machine_noise",
      "q09_grease_metal",
      "q10_prototype",
      "q11_vehicle",
      "q12_code_screen",
      "q13_vehicle_tools",
      "q14_inspect_object",
      "q15_crafted",
      "q16_visual",
      "q17_solo_screen",
      "q18_vehicle_restore",
    ]),
  },
  {
    id: "persona_electrical",
    targetProfessionId: "elektrotehnikis",
    rationale: "Elektriskās shēmas, droši mērījumi, kārtīga montāža un sistemātiska kļūmju meklēšana.",
    answers: createAnswers([
      "q01_computer_fix",
      "q02_circuit",
      "q03_finish",
      "q04_agri_machine",
      "q05_measurement",
      "q06_test",
      "q07_building_site",
      "q08_connectivity",
      "q09_site_dust",
      "q10_quality",
      "q11_electrical",
      "q12_code_screen",
      "q13_network_tools",
      "q14_safe_manual",
      "q15_immediate_repair",
      "q16_precise",
      "q17_solo_screen",
      "q18_smart_lab",
    ]),
  },
  {
    id: "persona_renewable_energy",
    targetProfessionId: "atjaunojamas_energetikas_tehnikis",
    rationale: "Elektrības sistēmas kopā ar montāžu ārā, mērījumiem un komandas darbu objektā.",
    answers: createAnswers([
      "q01_computer_fix",
      "q02_circuit",
      "q03_crop",
      "q04_agri_machine",
      "q05_measurement",
      "q06_build",
      "q07_field",
      "q08_machine_noise",
      "q09_weather",
      "q10_practical",
      "q11_electrical",
      "q12_code_screen",
      "q13_network_tools",
      "q14_safe_manual",
      "q15_immediate_repair",
      "q16_durable",
      "q17_solo_screen",
      "q18_field_trial",
    ]),
  },
];
